package com.vecturai.tools.preprocessor.steps

import com.vecturai.tools.preprocessor.PipelineStep
import com.vecturai.tools.preprocessor.model.ProcessingContext
import java.io.File

/**
 * Step 5: Export the generated data as JSON contract files.
 *
 * Writes the navigation graph, room data, and manifest to the
 * output directory in the format defined by docs/contracts/.
 *
 * TODO: Generate nav_graph.json from built graph
 * TODO: Generate rooms.json from detected rooms
 * TODO: Generate entrance_markers.json (requires manual marker placement config)
 * TODO: Generate manifest.json with version and checksums
 * TODO: Generate route_rendering.json with default rendering config
 */
class ExportContractsStep : PipelineStep {
    override val name = "Export Contracts"

    override fun execute(context: ProcessingContext) {
        if (!context.graphBuilt) {
            throw IllegalStateException("Graph not built — cannot export")
        }

        val outputDir = File(context.outputDir)
        if (!outputDir.exists()) {
            outputDir.mkdirs()
        }

        // TODO: Serialize generated data to JSON contract files
        val filesToExport = listOf(
            "manifest.json",
            "nav_graph.json",
            "rooms.json",
            "entrance_markers.json",
            "route_rendering.json",
        )

        for (fileName in filesToExport) {
            val file = File(outputDir, fileName)
            // TODO: Write actual generated JSON content
            file.writeText("{\n  \"_stub\": true,\n  \"_note\": \"Generated by nav-preprocessor v0.1.0\"\n}")
        }

        context.contractsExported = true
        context.exportedFiles = filesToExport
    }
}
