package com.Vectura AI.core.domain

import kotlinx.serialization.Serializable

/**
 * A node in the indoor navigation graph.
 *
 * Coordinates use the building-local coordinate system:
 * - Unit: meters
 * - Convention: Y-up, right-handed
 * - Floor plane: Y = 0 for single-floor MVP
 *
 * @property id Unique identifier (e.g., "n01", "entrance-main")
 * @property x X position in meters (building-local)
 * @property y Y position in meters (building-local, 0 = floor)
 * @property z Z position in meters (building-local)
 * @property type Node classification for semantic use
 * @property label Optional human-readable label
 * @property roomId If this node is inside/at-entry-of a room, the room ID
 */
@Serializable
data class NavNode(
    val id: String,
    val x: Double,
    val y: Double,
    val z: Double = 0.0,
    val type: NodeType = NodeType.WAYPOINT,
    val label: String? = null,
    val roomId: String? = null,
)

/**
 * Classification of graph nodes for semantic processing.
 */
@Serializable
enum class NodeType {
    WAYPOINT,
    ENTRANCE,
    ROOM_ENTRY,
    JUNCTION,
    POI,
}

/**
 * An edge connecting two [NavNode]s in the navigation graph.
 *
 * Edges are stored with a single direction (from → to).
 * [bidirectional] indicates whether traversal in both directions is allowed.
 *
 * @property id Unique edge identifier
 * @property from Source node ID
 * @property to Destination node ID
 * @property weight Edge weight / traversal cost (typically Euclidean distance in meters)
 * @property bidirectional If true, edge can also be traversed to → from
 * @property isAccessible Whether the edge is currently traversable
 */
@Serializable
data class NavEdge(
    val id: String = "",
    val from: String,
    val to: String,
    val weight: Double,
    val bidirectional: Boolean = true,
    val isAccessible: Boolean = true,
)

/**
 * Complete indoor navigation graph for a single floor.
 *
 * Generated by the nav-preprocessor from an authoring config.
 * Consumed at runtime by [RouteEngine] for pathfinding.
 *
 * @property buildingId Building this graph belongs to
 * @property floorId Floor identifier ("ground" for MVP)
 * @property nodes All navigable waypoints
 * @property edges All connections between waypoints
 * @property schemaVersion Schema version for forward compatibility
 */
@Serializable
data class NavGraph(
    val buildingId: String,
    val floorId: String = "ground",
    val nodes: List<NavNode>,
    val edges: List<NavEdge>,
    val schemaVersion: Int = 1,
) {
    /** Quick lookup of a node by its ID. */
    val nodeMap: Map<String, NavNode> by lazy {
        nodes.associateBy { it.id }
    }

    /**
     * Full adjacency list including reverse edges for bidirectional edges.
     * Each entry: nodeId → list of (neighborId, weight) pairs.
     */
    val adjacencyList: Map<String, List<NavEdge>> by lazy {
        val result = mutableMapOf<String, MutableList<NavEdge>>()
        for (edge in edges) {
            if (!edge.isAccessible) continue
            result.getOrPut(edge.from) { mutableListOf() }.add(edge)
            if (edge.bidirectional) {
                val reverse = edge.copy(from = edge.to, to = edge.from)
                result.getOrPut(edge.to) { mutableListOf() }.add(reverse)
            }
        }
        result
    }
}
